### ISSUE TITLE
Define Backend Project Requirements and  Create 15 tasks for project

### ISSUE THREAD

**Issue by yogeshtakeo** [allenvarughese22/AllenXmasCart#1]
Document detailed requirements for the e-commerce backend, including API endpoints, security needs, and database models.

- [x] Backend Project requirements documentation
- [x] Frontend Project requirements documentation
- [x] 15 tasks for the project
- [x] Initiation of the React application
- [x] Intiation of the Java Spring boot
- [x] Initiation of the Github in both backend and frontend

**Comment by allenvarughese22** [comment]
done
